export const translations = {
  en: {
    // NavBar
    navbar: {
      home: "Home",
      about: "About",
      services: "Services",
      gallery: "Gallery",
      videos: "Videos",
      photos: "Photos",
      destination: "Destination",
      westernProvince: "Western Province",
      easternProvince: "Eastern Province",
      northernProvince: "Northern Province",
      southernProvince: "Southern Province",
      kigaliCity: "KIGALI City",
    },
    // Footer
    footer: {
      siteName: "TEMBERA U RWANDA",
      slogan: "Discover the beauty of land of a thousand hills",
      quickLinks: "Quick links",
      destination: "Destination",
      contact: "Contact",
      home: "Home",
      contactNav: "Contact",
      services: "Services",
      about: "About",
      easternProvince: "EASTERN Province",
      westernProvince: "WESTERN Province",
      northernProvince: "NORTHERN Province",
      southernProvince: "SOUTHERN Province",
      kigaliCity: "KIGALI City",
      email: "ahantunyaburanga@gmail.com",
      phone: "0798818703",
      location: "KAGUGU KIGALI RWANDA",
      copyright: "© 2025 Visit Rwanda. All rights reserved",
    },
    // Home View
    home: {
      welcomeTitle: "Welcome to Rwanda",
      welcomeSubtitle: "Land of a Thousand Hills.",
      exploreCardTitle: "Explore",
      exploreCardText: "Discover beautiful parks, mountains, lakes, and wildlife in Rwanda.",
      exploreButton: "Explore Now",
      learnMoreCardTitle: "Learn More",
      learnMoreCardText: "Learn about Rwanda's culture, history, traditions, and tourism.",
      learnMoreButton: "Learn More",
      temberaTitle: "Tembera u Rwanda",
      temberaDescription: "Discover the beauty of Rwanda — the land of a thousand hills, breathtaking landscapes, rich culture, wildlife, and unforgettable adventures.",
      exploreRwanda: "Explore Rwanda",
      welcomeTitle2: "Welcome to Rwanda",
      welcomeText: "Rwanda is one of Africa's most beautiful countries, known for its green hills, clean cities, peaceful environment, and warm hospitality.",
      welcomeText2: "From the stunning Volcanoes National Park to the relaxing shores of Lake Kivu, Rwanda offers unforgettable experiences for tourists, adventurers, and nature lovers.",
      exploreRwanda2: "Explore Rwanda",
      amazingDestinations: "Amazing destinations waiting for you",
      volcanoes: "Volcanoes",
      volcanoesDesc: "Experience mountain hiking and discover the famous gorillas in Volcanoes National Park.",
      lakeKivu: "Lake Kivu",
      lakeKivuDesc: "Relax by the beautiful beaches and enjoy peaceful boat rides on Lake Kivu.",
      kigaliCity: "Kigali City",
      kigaliCityDesc: "Explore one of Africa's cleanest and safest cities filled with culture, art, and modern beauty.",
    },
    // About View
    about: {
      title: "Welcome to Rwanda",
      description: "Discover the beauty of Rwanda — the land of a thousand hills, breathtaking landscapes, rich culture, wildlife, and unforgettable adventures.",
      exploreRwanda: "Explore Rwanda",
      mainTitle: "Welcome to Rwanda",
      mainText: "Rwanda is one of Africa's most beautiful countries, known for its green hills, clean cities, peaceful environment, and warm hospitality.",
      mainText2: "From the stunning Volcanoes National Park to the relaxing shores of Lake Kivu, Rwanda offers unforgettable experiences for tourists, adventurers, and nature lovers.",
      exploreTitle: "Explore Rwanda",
      amazingDestinations: "Amazing destinations waiting for you",
      volcanoes: "Volcanoes",
      volcanoesDesc: "Experience mountain hiking and discover the famous gorillas in Volcanoes National Park.",
      lakeKivu: "Lake Kivu",
      lakeKivuDesc: "Relax by the beautiful beaches and enjoy peaceful boat rides on Lake Kivu.",
      kigaliCity: "Kigali City",
      kigaliCityDesc: "Explore one of Africa's cleanest and safest cities filled with culture, art, and modern beauty.",
    },
    // Contact View
    contact: {
      title: "Contact Us",
      subtitle: "We'd love to hear from you. Connect with Tembera U Rwanda.",
      phone: "Phone",
      phoneNumber: "+250 798 818 703",
      email: "Email",
      emailAddress: "tembera22@gmail.com",
      socialMedia: "Social Media",
      instagram: "Instagram: @tembera_u_rwanda",
      twitter: "X (Twitter): @tembera",
      siteName: "Tembera U Rwanda",
      description: "Discover Rwanda's breathtaking landscapes, mountain gorillas, beautiful lakes, rich culture, and unforgettable tourism experiences. We are here to help you explore the Land of a Thousand Hills.",
    },
    // Services View
    services: {
      title: "Our Services",
      subtitle: "Welcome to Tembera U Rwanda",
      gorillaTitle: "Gorilla Trekking Information",
      gorillaDesc: "We provide information about mountain gorilla trekking experiences in Volcanoes National Park and other wildlife adventures.",
      tourismTitle: "Tourism Guidance",
      tourismDesc: "Discover Rwanda's top attractions including Lake Kivu, Nyungwe Forest, Akagera National Park, and cultural heritage sites.",
      travelTitle: "Travel Recommendations",
      travelDesc: "Get recommendations on places to visit, activities to enjoy, and memorable experiences throughout Rwanda.",
      location: "📍 Our Location",
      locationCity: "Kigali, Rwanda",
      locationDesc: "We proudly promote tourism across Rwanda, the Land of a Thousand Hills.",
    },
    // Eastern Province View
    eastern: {
      title: "Welcome to Eastern Province",
      description: "Eastern Province is home to the famous Akagera National Park, Rwanda's largest national park. The park is known for its beautiful savannah landscapes, lakes, wetlands, and rich wildlife.",
      wildlifeText: "Visitors can enjoy game drives and spot the Big Five: lions, elephants, rhinos, buffaloes, and leopards. Akagera is one of Rwanda's most exciting tourist destinations.",
      lion: "Lion",
      lionDesc: "Lions are among the most famous animals found in Akagera National Park.",
      elephant: "Elephant",
      elephantDesc: "African elephants can be seen roaming freely across Akagera's plains.",
      giraffe: "Giraffe",
      giraffeDesc: "Giraffes are easily spotted thanks to their long necks and graceful appearance.",
      zebra: "Zebra",
      zebraDesc: "Zebras add beauty to the savannah with their striking black-and-white stripes.",
      rhino: "Rhino",
      rhinoDesc: "Rhinos are among the rare and protected animals found in Akagera.",
      buffalo: "Buffalo",
      buffaloDesc: "Buffaloes are powerful animals that live in large herds across the park.",
    },
    // Western Province View
    western: {
      title: "Welcome to Western Province",
      introText: "Discover the beauty of Rwanda's Western Province, home to the magnificent Lake Kivu, rolling green hills, vibrant culture, and unforgettable adventures.",
      lakeTitle: "Lake Kivu, Gisenyi",
      lakeDesc: "Lake Kivu is one of Africa's Great Lakes and one of Rwanda's most treasured natural attractions. Located in the Western Province, it stretches along Rwanda's border with the Democratic Republic of Congo. The city of Rubavu (formerly Gisenyi) is the most popular gateway to the lake and offers beautiful beaches, lakeside resorts, and stunning scenery.",
      lakeDesc2: "Visitors come from around the world to enjoy the peaceful waters, breathtaking sunsets, boat cruises, kayaking, swimming, fishing, and island tours. The lake is surrounded by green hills that create a spectacular landscape known as the 'Land of a Thousand Hills.'",
      naturalBeauty: "🌊 Natural Beauty",
      naturalBeautyDesc: "Lake Kivu offers crystal-clear waters, scenic shorelines, and breathtaking views of surrounding hills and islands.",
      activities: "🚤 Activities",
      activitiesDesc: "Enjoy boat rides, kayaking, fishing, swimming, beach walks, and unforgettable sunset cruises on the lake.",
      islands: "🏝 Islands",
      islandsDesc: "Explore beautiful islands such as Napoleon Island and Amahoro Island, each offering unique wildlife and natural attractions.",
      culture: "🎭 Culture",
      cultureDesc: "Experience local traditions, Rwandan hospitality, delicious food, music, and cultural performances near the lakeside communities.",
      whyVisit: "Why Visit Western Province?",
      whyVisitDesc: "Western Province is one of Rwanda's top tourism destinations. Beyond Lake Kivu, visitors can explore tea plantations, mountain landscapes, hiking trails, cultural heritage sites, and nearby attractions such as the beautiful forests around the region. Whether you seek relaxation, adventure, or cultural experiences, Western Province offers something memorable for every traveler.",
    },
    // Northern Province View
    northern: {
      title: "Welcome to Northern Province",
      subtitle: "Northern Province is home to Rwanda's famous Mountain Gorillas, breathtaking volcanoes, and the internationally celebrated Kwita Izina ceremony.",
      mountainGorillas: "Mountain Gorillas",
      mountainGorillasDesc: "Mountain gorillas are one of Rwanda's greatest treasures. They live in Volcanoes National Park and attract visitors from around the world who come to experience gorilla trekking.",
      volcanoesNationalPark: "Volcanoes National Park",
      volcanoesDesc: "Located in Musanze District, Volcanoes National Park is known for its stunning volcanic mountains, rich biodiversity, and conservation efforts that protect endangered gorillas.",
      kwitaIzina: "Kwita Izina",
      kwitaIzinaDesc: "Kwita Izina is Rwanda's annual gorilla naming ceremony. Newborn gorillas are given names that reflect Rwanda's culture, conservation achievements, and commitment to protecting wildlife.",
      aboutKwitaIzina: "About Kwita Izina",
      kwitaIzinaFullDesc: "Kwita Izina is inspired by the traditional Rwandan practice of naming children after birth. Every year, conservationists, community leaders, tourists, and international guests gather in Musanze to celebrate the birth of baby gorillas. The ceremony highlights Rwanda's success in wildlife conservation and promotes sustainable tourism.",
    },
    // Southern Province View
    southern: {
      title: "Welcome to Southern Province",
      description: "Southern Province is home to the famous Nyungwe Forest National Park, one of Africa's oldest rainforests. The forest is rich in biodiversity, featuring hundreds of bird species, primates, orchids, and beautiful hiking trails that attract visitors from around the world.",
      description2: "One of the most exciting attractions in Nyungwe is the Canopy Walkway. Suspended high above the forest floor, this walkway offers breathtaking views of the lush rainforest canopy, allowing visitors to experience nature from a unique perspective while enjoying unforgettable scenery.",
      nyungweForest: "Nyungwe Forest",
      nyungweForestDesc: "Explore one of Africa's oldest rainforests, home to diverse wildlife, waterfalls, and breathtaking hiking trails.",
      canopyWalkway: "Canopy Walkway",
      canopyWalkwayDesc: "Walk high above the rainforest and enjoy spectacular panoramic views of the treetops and surrounding mountains.",
      wildlifeNature: "Wildlife & Nature",
      wildlifeNatureDesc: "Discover chimpanzees, monkeys, colorful birds, and unique plant species living within the rich ecosystem of Nyungwe.",
    },
    // Kigali View
    kigali: {
      title: "Welcome to Kigali City",
      description: "Kigali is the capital city of Rwanda and one of the cleanest and fastest-growing cities in Africa. The city is known for modern buildings, technology, innovation, safety, and beautiful green hills.",
      description2: "Visitors enjoy exploring Kigali's modern infrastructure, cultural sites, conference centers, and world-class sports facilities such as BK Arena and Amahoro Stadium.",
      smartKigali: "Smart Kigali",
      smartKigaliDesc: "Kigali continues to grow as a smart city with modern technology, clean streets, reliable services, and innovative urban development.",
      bkArena: "BK Arena",
      bkArenaDesc: "BK Arena is one of East Africa's most modern indoor arenas, hosting basketball games, concerts, conferences, and international events.",
      amahoroStadium: "Amahoro Stadium",
      amahoroStadiumDesc: "Amahoro Stadium is Rwanda's national stadium and hosts football matches, ceremonies, and major national events.",
    },
    // Photos View
    photos: {
      title: "Rwanda Tourist Attractions",
      bkArena: "Bk Arena",
      mountainGorillas: "Mountain Gorillas",
      lakeKivu: "Lake Kivu",
      nyungweForest: "Nyungwe Forest",
      nyungweCanopyWalkway: "Nyungwe Canopy Walkway",
      akageranationalPark: "Akagera National Park",
      kigaliConventionCentre: "Kigali Convention Centre",
      kingsPalaceMuseum: "King's Palace Museum",
      twinLakes: "Twin Lakes (Burera & Ruhondo)",
      mountKarisimbi: "Mount Karisimbi",
    },
    // Videos View
    videos: {
      title: "Rwanda Cultural Songs",
      subtitle: "Enjoy some traditional Rwandan cultural music and dance performances.",
      intoreDance: "Intore Traditional Dance",
      rwandaCulturalPerformance: "Rwanda Cultural Performance",
      traditionalDrumming: "Traditional Drumming",
      culturalWeddingSongs: "Cultural Wedding Songs",
      intoreWarriorsDance: "Intore Warriors Dance",
      rwandaHeritageMusic: "Rwanda Heritage Music",
    },
  },

  fr: {
    // NavBar
    navbar: {
      home: "Accueil",
      about: "À propos",
      services: "Services",
      gallery: "Galerie",
      videos: "Vidéos",
      photos: "Photos",
      destination: "Destination",
      westernProvince: "Province de l'Ouest",
      easternProvince: "Province de l'Est",
      northernProvince: "Province du Nord",
      southernProvince: "Province du Sud",
      kigaliCity: "Ville de KIGALI",
    },
    // Footer
    footer: {
      siteName: "TEMBERA U RWANDA",
      slogan: "Découvrez la beauté du pays aux mille collines",
      quickLinks: "Liens rapides",
      destination: "Destination",
      contact: "Contact",
      home: "Accueil",
      contactNav: "Contact",
      services: "Services",
      about: "À propos",
      easternProvince: "Province de l'EST",
      westernProvince: "Province de l'OUEST",
      northernProvince: "Province du NORD",
      southernProvince: "Province du SUD",
      kigaliCity: "Ville de KIGALI",
      email: "ahantunyaburanga@gmail.com",
      phone: "0798818703",
      location: "KAGUGU KIGALI RWANDA",
      copyright: "© 2025 Visitez le Rwanda. Tous droits réservés",
    },
    // Home View
    home: {
      welcomeTitle: "Bienvenue au Rwanda",
      welcomeSubtitle: "Le pays aux mille collines.",
      exploreCardTitle: "Explorer",
      exploreCardText: "Découvrez les beaux parcs, montagnes, lacs et faune du Rwanda.",
      exploreButton: "Explorer maintenant",
      learnMoreCardTitle: "En savoir plus",
      learnMoreCardText: "Découvrez la culture, l'histoire, les traditions et le tourisme du Rwanda.",
      learnMoreButton: "En savoir plus",
      temberaTitle: "Tembera u Rwanda",
      temberaDescription: "Découvrez la beauté du Rwanda — le pays aux mille collines, des paysages spectaculaires, une riche culture, une faune sauvage et des aventures inoubliables.",
      exploreRwanda: "Explorez le Rwanda",
      welcomeTitle2: "Bienvenue au Rwanda",
      welcomeText: "Le Rwanda est l'un des plus beaux pays d'Afrique, connu pour ses collines verdoyantes, ses villes propres, son environnement paisible et l'hospitalité chaleureuse de ses habitants.",
      welcomeText2: "Du spectaculaire Parc National des Volcans aux rivages apaisants du Lac Kivu, le Rwanda offre des expériences inoubliables aux touristes, aventuriers et amoureux de la nature.",
      exploreRwanda2: "Explorez le Rwanda",
      amazingDestinations: "Des destinations incroyables vous attendent",
      volcanoes: "Volcans",
      volcanoesDesc: "Profitez de la randonnée en montagne et découvrez les fameux gorilles du Parc National des Volcans.",
      lakeKivu: "Lac Kivu",
      lakeKivuDesc: "Détendez-vous sur les belles plages et profitez de tranquilles croisières sur le Lac Kivu.",
      kigaliCity: "Ville de Kigali",
      kigaliCityDesc: "Explorez l'une des villes les plus propres et les plus sûres d'Afrique remplie de culture, d'art et de beauté moderne.",
    },
    // About View
    about: {
      title: "Bienvenue au Rwanda",
      description: "Découvrez la beauté du Rwanda — le pays aux mille collines, des paysages spectaculaires, une riche culture, une faune sauvage et des aventures inoubliables.",
      exploreRwanda: "Explorez le Rwanda",
      mainTitle: "Bienvenue au Rwanda",
      mainText: "Le Rwanda est l'un des plus beaux pays d'Afrique, connu pour ses collines verdoyantes, ses villes propres, son environnement paisible et l'hospitalité chaleureuse de ses habitants.",
      mainText2: "Du spectaculaire Parc National des Volcans aux rivages apaisants du Lac Kivu, le Rwanda offre des expériences inoubliables aux touristes, aventuriers et amoureux de la nature.",
      exploreTitle: "Explorez le Rwanda",
      amazingDestinations: "Des destinations incroyables vous attendent",
      volcanoes: "Volcans",
      volcanoesDesc: "Profitez de la randonnée en montagne et découvrez les fameux gorilles du Parc National des Volcans.",
      lakeKivu: "Lac Kivu",
      lakeKivuDesc: "Détendez-vous sur les belles plages et profitez de tranquilles croisières sur le Lac Kivu.",
      kigaliCity: "Ville de Kigali",
      kigaliCityDesc: "Explorez l'une des villes les plus propres et les plus sûres d'Afrique remplie de culture, d'art et de beauté moderne.",
    },
    // Contact View
    contact: {
      title: "Nous Contacter",
      subtitle: "Nous aimerions vous entendre. Connectez-vous avec Tembera U Rwanda.",
      phone: "Téléphone",
      phoneNumber: "+250 798 818 703",
      email: "Email",
      emailAddress: "tembera22@gmail.com",
      socialMedia: "Réseaux sociaux",
      instagram: "Instagram: @tembera_u_rwanda",
      twitter: "X (Twitter): @tembera",
      siteName: "Tembera U Rwanda",
      description: "Découvrez les paysages spectaculaires du Rwanda, les gorilles des montagnes, les beaux lacs, la riche culture et les expériences touristiques inoubliables. Nous sommes ici pour vous aider à explorer le Pays aux Mille Collines.",
    },
    // Services View
    services: {
      title: "Nos Services",
      subtitle: "Bienvenue à Tembera U Rwanda",
      gorillaTitle: "Informations sur la Randonnée avec les Gorilles",
      gorillaDesc: "Nous fournissons des informations sur les expériences de randonnée avec les gorilles des montagnes au Parc National des Volcans et d'autres aventures fauniques.",
      tourismTitle: "Conseils en Tourisme",
      tourismDesc: "Découvrez les principales attractions du Rwanda, notamment le Lac Kivu, la Forêt de Nyungwe, le Parc National d'Akagera et les sites patrimoniaux.",
      travelTitle: "Recommandations de Voyage",
      travelDesc: "Obtenez des recommandations sur les endroits à visiter, les activités à apprécier et les expériences mémorables dans tout le Rwanda.",
      location: "📍 Notre Localisation",
      locationCity: "Kigali, Rwanda",
      locationDesc: "Nous promouvons fièrement le tourisme dans tout le Rwanda, le Pays aux Mille Collines.",
    },
    // Eastern Province View
    eastern: {
      title: "Bienvenue à la Province de l'Est",
      description: "La Province de l'Est abrite le célèbre Parc National d'Akagera, le plus grand parc national du Rwanda. Le parc est connu pour ses beaux paysages de savane, ses lacs, ses zones humides et sa faune riche.",
      wildlifeText: "Les visiteurs peuvent profiter de safaris et observer le Grand Cinq : lions, éléphants, rhinocéros, buffles et léopards. Akagera est l'une des destinations touristiques les plus excitantes du Rwanda.",
      lion: "Lion",
      lionDesc: "Les lions sont parmi les animaux les plus célèbres du Parc National d'Akagera.",
      elephant: "Éléphant",
      elephantDesc: "Les éléphants d'Afrique peuvent être vus errant librement dans les plaines d'Akagera.",
      giraffe: "Girafe",
      giraffeDesc: "Les girafes sont facilement repérables grâce à leurs longs cous et leur allure gracieuse.",
      zebra: "Zèbre",
      zebraDesc: "Les zèbres ajoutent de la beauté à la savane avec leurs rayures noir et blanc frappantes.",
      rhino: "Rhinocéros",
      rhinoDesc: "Les rhinocéros sont parmi les animaux rares et protégés d'Akagera.",
      buffalo: "Buffle",
      buffaloDesc: "Les buffles sont des animaux puissants qui vivent en grands troupeaux dans le parc.",
    },
    // Western Province View
    western: {
      title: "Bienvenue à la Province de l'Ouest",
      introText: "Découvrez la beauté de la Province de l'Ouest du Rwanda, qui abrite le magnifique Lac Kivu, des collines verdoyantes, une culture dynamique et des aventures inoubliables.",
      lakeTitle: "Lac Kivu, Gisenyi",
      lakeDesc: "Le Lac Kivu est l'un des Grands Lacs d'Afrique et l'une des attractions naturelles les plus précieuses du Rwanda. Situé dans la Province de l'Ouest, il s'étend le long de la frontière du Rwanda avec la République Démocratique du Congo. La ville de Rubavu (anciennement Gisenyi) est la porte d'accès la plus populaire au lac et offre de belles plages, des complexes balnéaires et des paysages spectaculaires.",
      lakeDesc2: "Les visiteurs du monde entier viennent profiter des eaux paisibles, des couchers de soleil spectaculaires, des croisières en bateau, du kayak, de la natation, de la pêche et des visites d'îles. Le lac est entouré de collines verdoyantes qui créent un paysage spectaculaire connu sous le nom du 'Pays aux Mille Collines'.",
      naturalBeauty: "🌊 Beauté Naturelle",
      naturalBeautyDesc: "Le Lac Kivu offre des eaux cristallines, des côtes pittoresques et des vues spectaculaires des collines et îles environnantes.",
      activities: "🚤 Activités",
      activitiesDesc: "Profitez de promenades en bateau, kayak, pêche, natation, promenades en plage et inoubliables croisières au coucher de soleil sur le lac.",
      islands: "🏝 Îles",
      islandsDesc: "Explorez de belles îles comme l'Île de Napoléon et l'Île d'Amahoro, offrant chacune des attractions fauniques et naturelles uniques.",
      culture: "🎭 Culture",
      cultureDesc: "Découvrez les traditions locales, l'hospitalité rwandaise, la délicieuse cuisine, la musique et les performances culturelles près des communautés du bord du lac.",
      whyVisit: "Pourquoi Visiter la Province de l'Ouest?",
      whyVisitDesc: "La Province de l'Ouest est l'une des principales destinations touristiques du Rwanda. Au-delà du Lac Kivu, les visiteurs peuvent explorer les plantations de thé, les paysages montagneux, les sentiers de randonnée, les sites patrimoniaux et les attractions à proximité comme les beaux forêts de la région. Que vous recherchiez la détente, l'aventure ou des expériences culturelles, la Province de l'Ouest offre quelque chose de mémorable pour chaque voyageur.",
    },
    // Northern Province View
    northern: {
      title: "Bienvenue à la Province du Nord",
      subtitle: "La Province du Nord abrite les célèbres Gorilles des Montagnes du Rwanda, des volcans spectaculaires et la cérémonie Kwita Izina célébrée internationalement.",
      mountainGorillas: "Gorilles des Montagnes",
      mountainGorillasDesc: "Les gorilles des montagnes sont l'un des plus grands trésors du Rwanda. Ils vivent au Parc National des Volcans et attirent des visiteurs du monde entier qui viennent faire l'expérience de la randonnée avec les gorilles.",
      volcanoesNationalPark: "Parc National des Volcans",
      volcanoesDesc: "Situé dans le District de Musanze, le Parc National des Volcans est connu pour ses spectaculaires montagnes volcaniques, sa riche biodiversité et ses efforts de conservation pour protéger les gorilles en danger.",
      kwitaIzina: "Kwita Izina",
      kwitaIzinaDesc: "Kwita Izina est la cérémonie annuelle de nommage des gorilles du Rwanda. Les jeunes gorilles reçoivent des noms qui reflètent la culture rwandaise, les réalisations en matière de conservation et l'engagement envers la protection de la faune.",
      aboutKwitaIzina: "À Propos de Kwita Izina",
      kwitaIzinaFullDesc: "Kwita Izina s'inspire de la pratique rwandaise traditionnelle de nommer les enfants après leur naissance. Chaque année, des conservationnistes, des leaders communautaires, des touristes et des invités internationaux se réunissent à Musanze pour célébrer la naissance des jeunes gorilles. La cérémonie souligne le succès du Rwanda en matière de conservation de la faune et promeut le tourisme durable.",
    },
    // Southern Province View
    southern: {
      title: "Bienvenue à la Province du Sud",
      description: "La Province du Sud abrite le célèbre Parc National de la Forêt de Nyungwe, l'une des plus anciennes forêts tropicales d'Afrique. La forêt est riche en biodiversité, avec des centaines d'espèces d'oiseaux, de primates, d'orchidées et de beaux sentiers de randonnée qui attirent les visiteurs du monde entier.",
      description2: "L'une des attractions les plus excitantes de Nyungwe est la Passerelle Aérienne. Suspendue haut au-dessus du sol de la forêt, cette passerelle offre des vues spectaculaires de la canopée luxuriante de la forêt tropicale, permettant aux visiteurs d'expérimenter la nature sous une perspective unique tout en profitant de paysages inoubliables.",
      nyungweForest: "Forêt de Nyungwe",
      nyungweForestDesc: "Explorez l'une des plus anciennes forêts tropicales d'Afrique, riche de faune diverse, de cascades et de spectaculaires sentiers de randonnée.",
      canopyWalkway: "Passerelle Aérienne",
      canopyWalkwayDesc: "Marchez haut au-dessus de la forêt tropicale et profitez des vues panoramiques spectaculaires des cimes des arbres et des montagnes environnantes.",
      wildlifeNature: "Faune et Nature",
      wildlifeNatureDesc: "Découvrez les chimpanzés, les singes, les oiseaux colorés et les espèces de plantes uniques vivant dans le riche écosystème de Nyungwe.",
    },
    // Kigali View
    kigali: {
      title: "Bienvenue à la Ville de Kigali",
      description: "Kigali est la capitale du Rwanda et l'une des villes les plus propres et les plus en croissance d'Afrique. La ville est connue pour ses bâtiments modernes, la technologie, l'innovation, la sécurité et ses belles collines verdoyantes.",
      description2: "Les visiteurs aiment explorer les infrastructures modernes de Kigali, les sites culturels, les centres de conférences et les installations sportives de classe mondiale comme la BK Arena et le Stade Amahoro.",
      smartKigali: "Kigali Intelligente",
      smartKigaliDesc: "Kigali continue de croître en tant que ville intelligente avec la technologie moderne, les rues propres, les services fiables et le développement urbain innovant.",
      bkArena: "BK Arena",
      bkArenaDesc: "BK Arena est l'une des arènes couvertes les plus modernes d'Afrique de l'Est, accueillant des matchs de basketball, des concerts, des conférences et des événements internationaux.",
      amahoroStadium: "Stade Amahoro",
      amahoroStadiumDesc: "Le Stade Amahoro est le stade national du Rwanda et accueille des matchs de football, des cérémonies et des événements nationaux majeurs.",
    },
    // Photos View
    photos: {
      title: "Attractions Touristiques du Rwanda",
      bkArena: "Arène BK",
      mountainGorillas: "Gorilles des Montagnes",
      lakeKivu: "Lac Kivu",
      nyungweForest: "Forêt de Nyungwe",
      nyungweCanopyWalkway: "Passerelle Aérienne de Nyungwe",
      akageranationalPark: "Parc National d'Akagera",
      kigaliConventionCentre: "Centre de Conventions de Kigali",
      kingsPalaceMuseum: "Musée du Palais Royal",
      twinLakes: "Lacs Jumeaux (Burera et Ruhondo)",
      mountKarisimbi: "Mont Karisimbi",
    },
    // Videos View
    videos: {
      title: "Chansons Culturelles du Rwanda",
      subtitle: "Profitez de quelques performances traditionnelles de musique et de danse culturelle rwandaise.",
      intoreDance: "Danse Intore Traditionnelle",
      rwandaCulturalPerformance: "Performance Culturelle Rwandaise",
      traditionalDrumming: "Tambours Traditionnels",
      culturalWeddingSongs: "Chansons de Mariage Culturelles",
      intoreWarriorsDance: "Danse des Guerriers Intore",
      rwandaHeritageMusic: "Musique Patrimoniale du Rwanda",
    },
  },

  rw: {
    // NavBar
    navbar: {
      home: "Ahabanza",
      about: "Kubwira",
      services: "Inzira",
      gallery: "Ifoto",
      videos: "Ivideo",
      photos: "Ifoto",
      destination: "Nzira",
      westernProvince: "Intara y'Iburengerazuba",
      easternProvince: "Intara y'Iburasirazuba",
      northernProvince: "Intara y'Amajyaruguru",
      southernProvince: "Intara y'Amajyepfo",
      kigaliCity: "Umujyi wa KIGALI",
    },
    // Footer
    footer: {
      siteName: "TEMBERA U RWANDA",
      slogan: "Reba ikirezi cy'u Rwanda - igihugu c'imigozi ibihumbi",
      quickLinks: "Ihuza vuba",
      destination: "Nzira",
      contact: "Menya",
      home: "Ahabanza",
      contactNav: "Menya",
      services: "Inzira",
      about: "Kubwira",
      easternProvince: "Intara y'IBURASIRAZUBA",
      westernProvince: "Intara y'IBURENGERAZUBA",
      northernProvince: "Intara y'AMAJYARUGURU",
      southernProvince: "Intara y'AMAJYEPFO",
      kigaliCity: "Umujyi wa KIGALI",
      email: "ahantunyaburanga@gmail.com",
      phone: "0798818703",
      location: "KAGUGU KIGALI RWANDA",
      copyright: "© 2025 Teri u Rwanda. Ibyemezo byose biri bitegereje.",
    },
    // Home View
    home: {
      welcomeTitle: "Murakaza neza u Rwanda",
      welcomeSubtitle: "Igihugu c'imigozi ibihumbi.",
      exploreCardTitle: "Kunararira",
      exploreCardText: "Reba inyarwanda nziza, umusozi, ibiruzo, n'inyamabanga z'u Rwanda.",
      exploreButton: "Kunararira ubwayo",
      learnMoreCardTitle: "Menya Cyane",
      learnMoreCardText: "Menya ibitabo, imbere, imibanire, n'inzira z'u Rwanda.",
      learnMoreButton: "Menya Cyane",
      temberaTitle: "Tembera u Rwanda",
      temberaDescription: "Reba ikirezi cy'u Rwanda — igihugu c'imigozi ibihumbi, inyarwanda nziza, umuco mwinshi, inyamabanga, n'ibikoresho bitahitana.",
      exploreRwanda: "Kunararira u Rwanda",
      welcomeTitle2: "Murakaza neza u Rwanda",
      welcomeText: "U Rwanda ni igihugu c'ikirezi muri Africa, kiranditse umurongo w'imigozi, imijyi iremereye, amahoro, n'ubwenge bw'Abarwanda.",
      welcomeText2: "Kuva Inyarwanda nkizi z'u Birutso kugeza ku Ziwa Kivu, u Rwanda gutanga ibikoresho bitahitana ku barwabutwa, abapikari, n'abantu bakunda umushantu.",
      exploreRwanda2: "Kunararira u Rwanda",
      amazingDestinations: "Inzira nziza zirimwo",
      volcanoes: "Birutso",
      volcanoesDesc: "Umera mu buhanga n'ureba gorila izamuka mu Inyarwanda nkizi z'u Birutso.",
      lakeKivu: "Ziwa Kivu",
      lakeKivuDesc: "Mahoro mu nzira nziza z'u Ziwa Kivu n'ubwihishe bw'ibwato.",
      kigaliCity: "Umujyi wa Kigali",
      kigaliCityDesc: "Reba umujyi uhamba imbere muri Africa, ureme, numushantu, n'ubwenge.",
    },
    // About View
    about: {
      title: "Murakaza neza u Rwanda",
      description: "Reba ikirezi cy'u Rwanda — igihugu c'imigozi ibihumbi, inyarwanda nziza, umuco mwinshi, inyamabanga, n'ibikoresho bitahitana.",
      exploreRwanda: "Kunararira u Rwanda",
      mainTitle: "Murakaza neza u Rwanda",
      mainText: "U Rwanda ni igihugu c'ikirezi muri Africa, kiranditse umurongo w'imigozi, imijyi iremereye, amahoro, n'ubwenge bw'Abarwanda.",
      mainText2: "Kuva Inyarwanda nkizi z'u Birutso kugeza ku Ziwa Kivu, u Rwanda gutanga ibikoresho bitahitana ku barwabutwa, abapikari, n'abantu bakunda umushantu.",
      exploreTitle: "Kunararira u Rwanda",
      amazingDestinations: "Inzira nziza zirimwo",
      volcanoes: "Birutso",
      volcanoesDesc: "Umera mu buhanga n'ureba gorila izamuka mu Inyarwanda nkizi z'u Birutso.",
      lakeKivu: "Ziwa Kivu",
      lakeKivuDesc: "Mahoro mu nzira nziza z'u Ziwa Kivu n'ubwihishe bw'ibwato.",
      kigaliCity: "Umujyi wa Kigali",
      kigaliCityDesc: "Reba umujyi uhamba imbere muri Africa, ureme, numushantu, n'ubwenge.",
    },
    // Contact View
    contact: {
      title: "Tumenya",
      subtitle: "Nashaka kumva ijwi ryacu. Menya Tembera U Rwanda.",
      phone: "Telephone",
      phoneNumber: "+250 798 818 703",
      email: "Imeli",
      emailAddress: "tembera22@gmail.com",
      socialMedia: "Sosyali Media",
      instagram: "Instagram: @tembera_u_rwanda",
      twitter: "X (Twitter): @tembera",
      siteName: "Tembera U Rwanda",
      description: "Reba inyarwanda nziza z'u Rwanda, gorila izamuka, ziwa nziza, umuco, n'ibikoresho bitahitana. Turi hano kugufasha kunararira igihugu c'imigozi ibihumbi.",
    },
    // Services View
    services: {
      title: "Inzira Zitugira",
      subtitle: "Murakaza neza kuri Tembera U Rwanda",
      gorillaTitle: "Amakuru Ku Kwengera Gorila",
      gorillaDesc: "Tunatanga amakuru ku kwengera gorila mu Inyarwanda nkizi z'u Birutso n'ibindi bikoresho.",
      tourismTitle: "Ubwiyunge bw'Inzira",
      tourismDesc: "Reba inzira nziza z'u Rwanda, Ziwa Kivu, Karongi, Akagera, n'ibindi bisoro.",
      travelTitle: "Icyubahiro cyo Guhura",
      travelDesc: "Pona ibiciro n'ibikoresho nziza muri buri nzira y'u Rwanda.",
      location: "📍 Aho Twahereza",
      locationCity: "Kigali, Rwanda",
      locationDesc: "Turatanga inyarwanda nziza z'u Rwanda mu bihugu byose.",
    },
    // Eastern Province View
    eastern: {
      title: "Murakaza Neza Intara y'Iburasirazuba",
      description: "Intara y'Iburasirazuba ifite Akagera, inyarwanda nziza y'u Rwanda. Hako haturikira inyamabanga nziza n'ibinyabuzima.",
      wildlifeText: "Barwabutwa barashobora kureba intambo, nzani, inzira, n'ibindi binini byinshi. Akagera ni nzira nziza y'u Rwanda.",
      lion: "Intambo",
      lionDesc: "Intambo nziza muri Akagera.",
      elephant: "Nzani",
      elephantDesc: "Nzani z'Africa zisumba hejuru mu Akagera.",
      giraffe: "Twiga",
      giraffeDesc: "Twiga ishobora kwiyikwa ku mwanya w'uruvumbi rw'umutwe.",
      zebra: "Impisi",
      zebraDesc: "Impisi ziza igihugu k'umusharara.",
      rhino: "Imifo",
      rhinoDesc: "Imifo ni inyamabanga zahinduka.",
      buffalo: "Inyamabange",
      buffaloDesc: "Inyamabange ziryama ubwoko bunini.",
    },
    // Western Province View
    western: {
      title: "Murakaza Neza Intara y'Iburengerazuba",
      introText: "Reba ikirezi cy'Intara y'Iburengerazuba, ifite Ziwa Kivu, imigozi, umuco, n'ibikoresho bitahitana.",
      lakeTitle: "Ziwa Kivu, Gisenyi",
      lakeDesc: "Ziwa Kivu ni ziwa rinini riri muri Africa n'i Rwanda. Rihereza kurikiza inzira ya Poloponi. Umujyi wa Gisenyi ni nzira yibuku kuri ziwa. Hako haturikira inzira nziza, inyarwanda, n'ikinini.",
      lakeDesc2: "Abantu b'isi baraje kuri ziwa kugira neza, kureba inyuma y'inyusi, kwiyumba mu ngara, kuguhiga, n'ikinini. Ziwa rifata imigozi ihasi ifite ibirezi byinshi.",
      naturalBeauty: "🌊 Ikirezi Cy'Inyarwanda",
      naturalBeautyDesc: "Ziwa Kivu rifite amazi mahoro, inzira nziza, n'ibirezi byinshi.",
      activities: "🚤 Ibikoresho",
      activitiesDesc: "Guhura mu ngara, kuguhiga, kurya mu mirama, n'ikinini.",
      islands: "🏝 Cinika",
      islandsDesc: "Reba cinika nziza n'ibinyabuzima.",
      culture: "🎭 Umuco",
      cultureDesc: "Menya umuco w'Abarwanda, ibiribwa, n'inzira.",
      whyVisit: "Kuki Wiyunge Intara y'Iburengerazuba?",
      whyVisitDesc: "Intara y'Iburengerazuba ni nzira nziza y'u Rwanda. Haturikira Ziwa Kivu, barwabutwa barashobora kureba ikinini, ubwenge, nubindi. Niba ushaka mahoro, ibikoresho, cyangwa umuco, Intara y'Iburengerazuba ifite ibintu byinshi nziza.",
    },
    // Northern Province View
    northern: {
      title: "Murakaza Neza Intara y'Amajyaruguru",
      subtitle: "Intara y'Amajyaruguru ifite gorila izamuka, Birutso, n'indagyire ya Kwita Izina.",
      mountainGorillas: "Gorila Izamuka",
      mountainGorillasDesc: "Gorila izamuka ni inyamabanga nziza y'u Rwanda. Batuye mu Inyarwanda nkizi z'u Birutso. Abantu b'isi baraje kwiyigira.",
      volcanoesNationalPark: "Inyarwanda nkizi z'u Birutso",
      volcanoesDesc: "Inyarwanda nkizi z'u Birutso ifite birutso byinshi, inyamabanga, n'ubwiyunge.",
      kwitaIzina: "Kwita Izina",
      kwitaIzinaDesc: "Kwita Izina ni indagyire y'aha mwaka ya gitorero ry'imigozi. Gorila zinini zitekerezwa izina.",
      aboutKwitaIzina: "Kubwira Kwita Izina",
      kwitaIzinaFullDesc: "Kwita Izina ni ibikoresho by'Abarwanda. Buri mwaka, abashyira inyamabanga, abayobozi, n'abantu b'isi bashyirwamo izina. Indagyire iratanga agaciro ku bwiyunge.",
    },
    // Southern Province View
    southern: {
      title: "Murakaza Neza Intara y'Amajyepfo",
      description: "Intara y'Amajyepfo ifite Karongi, inyarwanda nkizi y'Africa. Hako haturikira inyamabanga nziza, ibyavu, n'inzira z'ubwiyunge.",
      description2: "Inzira nziza muri Karongi ni umwira w'imigozi. Umuntu asumba haruguru mu migozi n'areba ikinini cy'inyarwanda.",
      nyungweForest: "Karongi",
      nyungweForestDesc: "Reba Karongi, inyarwanda nkizi y'Africa, ifite inyamabanga nziza n'inzira z'ubwiyunge.",
      canopyWalkway: "Umwira w'Imigozi",
      canopyWalkwayDesc: "Wungira haruguru mu migozi n'urebe inyarwanda nziza.",
      wildlifeNature: "Inyamabanga n'Inyarwanda",
      wildlifeNatureDesc: "Reba senzimbi, ingagi, inyoni, n'ibinyabuzima by'inyarwanda.",
    },
    // Kigali View
    kigali: {
      title: "Murakaza Neza Umujyi wa Kigali",
      description: "Kigali ni umujyi w'u Rwanda, ureme, n'uhamba imbere. Hari ibikorwa n'ubwenge.",
      description2: "Abantu baraje Kigali kugira neza, kureba ibitabo, n'ibindi bisoro.",
      smartKigali: "Kigali Itunzwe Neza",
      smartKigaliDesc: "Kigali ihambahambira n'ubwiyunge, umvugo, n'ibikoresho by'ubwenge.",
      bkArena: "BK Arena",
      bkArenaDesc: "BK Arena ni hali nziza y'ubwikinini muri Africa. Hako hakoreshwa mu bwikinini, inzira, n'ibindi bisoro.",
      amahoroStadium: "Umwanya wa Amahoro",
      amahoroStadiumDesc: "Umwanya wa Amahoro ni umwanya w'igihugu, wakoreshwa mu mpira n'ibindi bisoro.",
    },
    // Photos View
    photos: {
      title: "Inzira Nziza z'u Rwanda",
      bkArena: "BK Arena",
      mountainGorillas: "Gorila Izamuka",
      lakeKivu: "Ziwa Kivu",
      nyungweForest: "Karongi",
      nyungweCanopyWalkway: "Umwira w'Karongi",
      akageranationalPark: "Akagera",
      kigaliConventionCentre: "Ihali ry'Ubwiyunge",
      kingsPalaceMuseum: "Ubwami",
      twinLakes: "Ziwa Zombi",
      mountKarisimbi: "Umusozi wa Karisimbi",
    },
    // Videos View
    videos: {
      title: "Inzira z'Umuco w'u Rwanda",
      subtitle: "Reba inzira z'umuco n'inzira.",
      intoreDance: "Inzira ya Intore",
      rwandaCulturalPerformance: "Inzira y'Umuco w'u Rwanda",
      traditionalDrumming: "Inzira y'Ingoma",
      culturalWeddingSongs: "Inzira z'Urwaniro",
      intoreWarriorsDance: "Inzira y'Intore Zimwe",
      rwandaHeritageMusic: "Inzira y'Imbere y'u Rwanda",
    },
  },
};

export default translations;
